### ISSUE TITLE
Doesn't seem to move overdue to today.

### ISSUE THREAD

**Issue by noisufnoc** [agladky/todoist-overdue-alfred#2]
I opened in debug console, says that my tasks are being moved but they actually don't move in todoist.

> [2018-03-12 15:25:21][input.keyword] Processing output of 'utility.argument' with arg ''
> [2018-03-12 15:25:21][utility.argument] Processing output of 'action.script' with arg ''
> [2018-03-12 15:25:22][action.script] Processing output of 'output.notification' with arg 'Tasks successfully moved'

Thoughts?

**Comment by agladky** [comment]
Try to regenerate token in todoist and replace it in the workflow.

**Comment by noisufnoc** [comment]
no such luck, I just tried a new token

**Comment by agladky** [comment]
Ok, I updated some dependencies, this may help. New workflow: https://github.com/agladky/todoist-overdue-alfred/blob/master/Todoist%20overdue.alfredworkflow

**Comment by noisufnoc** [comment]
I tried the new version, looks like it's complaining about urllib3

> [2018-03-14 10:23:24][input.keyword] Processing output of 'utility.argument' with arg ''
> [2018-03-14 10:23:24][utility.argument] Processing output of 'action.script' with arg ''
> [2018-03-14 10:23:25][ERROR: action.script] Traceback (most recent call last):
>   File "todoist_overdue.py", line 13, in <module>
>     from todoist import TodoistAPI
>   File "/Users/noisufnoc/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.82048476-481D-43EC-8AEA-6515019BF74A/lib/todoist/__init__.py", line 1, in <module>
>     from .api import TodoistAPI
>   File "/Users/noisufnoc/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.82048476-481D-43EC-8AEA-6515019BF74A/lib/todoist/api.py", line 4, in <module>
>     import requests
>   File "/Users/noisufnoc/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.82048476-481D-43EC-8AEA-6515019BF74A/lib/requests/__init__.py", line 43, in <module>
>     import urllib3
> ImportError: No module named urllib3
> [2018-03-14 10:23:25][action.script] Processing output of 'output.notification' with arg ''

**Comment by agladky** [comment]
Sorry for that, I fixed it. Try to download again, please.

**Comment by noisufnoc** [comment]
> [2018-03-15 10:11:59][input.keyword] Processing output of 'utility.argument' with arg ''
> [2018-03-15 10:11:59][utility.argument] Processing output of 'action.script' with arg ''
> [2018-03-15 10:11:59][ERROR: action.script] Traceback (most recent call last):
>   File "todoist_overdue.py", line 13, in <module>
>     from todoist import TodoistAPI
>   File "/Users/noisufnoc/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.82048476-481D-43EC-8AEA-6515019BF74A/lib/todoist/__init__.py", line 1, in <module>
>     from .api import TodoistAPI
>   File "/Users/noisufnoc/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.82048476-481D-43EC-8AEA-6515019BF74A/lib/todoist/api.py", line 4, in <module>
>     import requests
>   File "/Users/noisufnoc/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.82048476-481D-43EC-8AEA-6515019BF74A/lib/requests/__init__.py", line 44, in <module>
>     import chardet
> ImportError: No module named chardet
> [2018-03-15 10:11:59][action.script] Processing output of 'output.notification' with arg ''

**Comment by agladky** [comment]
I think I need to rebuild the workflow after my vacation.
For now, try to download for last time. I added all necessary libraries.

**Comment by noisufnoc** [comment]
Thank you for your help.  I tried the latest version, no errors but no tasks were moved.

**Comment by noisufnoc** [comment]
So I grabbed your python code and started walking through it, it seems that I dont get any overdue items at this point:

https://github.com/agladky/todoist-overdue-alfred/blob/master/todoist-overdue-alfred/todoist_overdue.py#L21

I'm not sure if it's my account or what.  Right now I have many items in the todoist UI as 'overdue' but when I query the api for 'overdue' I get an empty list.
